export type ObjectCategory =
  | "Quasar"
  | "Neutron star"
  | "Black hole"
  | "Stellar remnant"
  | "Unusual star"
  | "Supergiant"
  | "Variable star"
  | "Dwarf star";
export type ObjectVisual =
  | "cloud"
  | "shell"
  | "bipolar"
  | "jet"
  | "pulsar"
  | "blackhole"
  | "star"
  | "remnant";

export type ObservedObject = {
  id: string;
  name: string;
  aliases: string[];
  category: ObjectCategory;
  subtype: string;
  distance: number;
  l: number;
  b: number;
  diameterLy: number;
  visual: ObjectVisual;
  color: string;
  accent: string;
  observed: string;
  properties: string[];
  description: string;
  visualNote: string;
  source: string;
};

const o = (x: ObservedObject) => x;
export const OBSERVED_OBJECTS: ObservedObject[] = [
  o({
    id: "3c273",
    name: "3C 273",
    aliases: ["PGC 41121"],
    category: "Quasar",
    subtype: "Optically bright quasar",
    distance: 2.4e9,
    l: 290,
    b: 64.4,
    diameterLy: 200000,
    visual: "jet",
    color: "#dff2ff",
    accent: "#78a9ff",
    observed: "Unresolved nucleus; optical/X-ray jet",
    properties: ["Redshift z=0.158", "First identified quasar", "Jet ≈200,000 ly"],
    description:
      "A brilliant active galactic nucleus powered by matter falling toward a supermassive black hole, with a large relativistic jet.",
    visualNote: "The central engine is unresolved; its disk and jet are enhanced for inspection.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "3c279",
    name: "3C 279",
    aliases: ["4C -05.55"],
    category: "Quasar",
    subtype: "Blazar / flat-spectrum quasar",
    distance: 5.4e9,
    l: 305.1,
    b: 57.1,
    diameterLy: 100000,
    visual: "jet",
    color: "#fff2d8",
    accent: "#759cff",
    observed: "Gamma-ray, radio and optical",
    properties: ["Redshift z=0.536", "Jet points near Earth", "Apparent superluminal motion"],
    description:
      "A rapidly variable blazar whose relativistic jet is aimed close to our line of sight.",
    visualNote: "Jet motion is relativistic projection; the model is illustrative.",
    source: "NASA Fermi / VLBI observations",
  }),
  o({
    id: "mrk231",
    name: "Markarian 231",
    aliases: ["Mrk 231", "UGC 8058"],
    category: "Quasar",
    subtype: "Nearest known quasar / ULIRG",
    distance: 581e6,
    l: 196.5,
    b: 72.9,
    diameterLy: 100000,
    visual: "jet",
    color: "#ffe0bb",
    accent: "#78a9e8",
    observed: "Ultraviolet, visible and infrared",
    properties: ["Distance ≈581 Mly", "Powerful molecular outflow", "Disturbed host galaxy"],
    description:
      "The nearest quasar, embedded in a luminous merging galaxy and driving a powerful outflow.",
    visualNote:
      "The luminous nucleus is exaggerated; a proposed binary black hole remains uncertain.",
    source: "NASA Hubble",
  }),
  o({
    id: "ton618",
    name: "TON 618",
    aliases: ["FBQS J122824.9+312837"],
    category: "Quasar",
    subtype: "Hyperluminous quasar",
    distance: 10.4e9,
    l: 187.4,
    b: 83,
    diameterLy: 150000,
    visual: "jet",
    color: "#ffd9bd",
    accent: "#8da5ff",
    observed: "Unresolved optical point and spectrum",
    properties: [
      "Redshift z≈2.219",
      "Ultramassive black-hole estimate",
      "Seen billions of years in the past",
    ],
    description:
      "An exceptionally luminous distant quasar associated with one of the largest published black-hole mass estimates.",
    visualNote: "Its exact black-hole mass is model-dependent; the source is unresolved.",
    source: "NASA/IPAC catalogues and peer-reviewed spectroscopy",
  }),
  o({
    id: "crab-pulsar",
    name: "Crab Pulsar",
    aliases: ["PSR B0531+21"],
    category: "Neutron star",
    subtype: "Young rotation-powered pulsar",
    distance: 6500,
    l: 184.6,
    b: -5.8,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#dff7ff",
    accent: "#4bbfff",
    observed: "Radio through gamma ray",
    properties: ["Spin period 33 ms", "Diameter ≈20 km", "Powers the Crab Nebula"],
    description:
      "The collapsed stellar core left by SN 1054, sweeping radiation beams across Earth about 30 times each second.",
    visualNote: "The star and beams are enormously enlarged for visibility.",
    source: "NASA Chandra",
  }),
  o({
    id: "vela",
    name: "Vela Pulsar",
    aliases: ["PSR B0833−45"],
    category: "Neutron star",
    subtype: "Young pulsar",
    distance: 960,
    l: 263.6,
    b: -2.8,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#e6fbff",
    accent: "#4b9fff",
    observed: "Radio, optical, X-ray and gamma ray",
    properties: ["Spin period 89 ms", "Inside the Vela remnant", "X-ray torus and jets"],
    description:
      "A nearby young neutron star whose wind creates moving arcs and jet-like X-ray structures.",
    visualNote: "The compact star and magnetic beams are not rendered to scale.",
    source: "NASA Chandra / Fermi",
  }),
  o({
    id: "b1919",
    name: "First Pulsar",
    aliases: ["PSR B1919+21", "CP 1919", "LGM-1"],
    category: "Neutron star",
    subtype: "Radio pulsar",
    distance: 2283,
    l: 55.8,
    b: 3.5,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#f2fbff",
    accent: "#8fc7ff",
    observed: "Radio pulses",
    properties: ["Spin period 1.337 s", "Discovered in 1967", "First recognized pulsar"],
    description:
      "The first pulsar ever identified, discovered by Jocelyn Bell Burnell through its exceptionally regular radio pulses.",
    visualNote: "Radio beams are an explanatory visualization, not visible light.",
    source: "NRAO / peer-reviewed discovery record",
  }),
  o({
    id: "sgr1806",
    name: "SGR 1806−20",
    aliases: ["SGR 1806-20"],
    category: "Neutron star",
    subtype: "Magnetar",
    distance: 50000,
    l: 9.9,
    b: -0.2,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#f7eeff",
    accent: "#d267ff",
    observed: "X-ray and gamma ray",
    properties: ["Magnetic field ≈10¹⁵ G", "Giant flare in 2004", "Distance is highly uncertain"],
    description:
      "An intensely magnetized neutron star that produced the brightest extrasolar gamma-ray flare yet recorded.",
    visualNote:
      "Magnetic loops and scale are illustrative; distance estimates span roughly 28–50 kly.",
    source: "NASA Goddard / Chandra",
  }),
  o({
    id: "j0348",
    name: "PSR J0348+0432",
    aliases: ["J0348+0432"],
    category: "Neutron star",
    subtype: "Massive neutron-star binary",
    distance: 6500,
    l: 183.3,
    b: -36.8,
    diameterLy: 2.7e-12,
    visual: "pulsar",
    color: "#e8f4ff",
    accent: "#77a8ff",
    observed: "Radio timing and optical companion",
    properties: ["Mass 2.01 ± 0.04 M☉", "White-dwarf companion", "Tests strong-field gravity"],
    description:
      "A precisely weighed, unusually massive neutron star in a compact binary used to test general relativity.",
    visualNote: "Both bodies and their separation are enhanced for close viewing.",
    source: "Peer-reviewed radio timing / ESO",
  }),
  o({
    id: "sgr-a",
    name: "Sagittarius A*",
    aliases: ["Sgr A*"],
    category: "Black hole",
    subtype: "Milky Way central supermassive black hole",
    distance: 26673,
    l: 0,
    b: 0,
    diameterLy: 1.3e-5,
    visual: "blackhole",
    color: "#f59a48",
    accent: "#fff0be",
    observed: "Radio interferometry at 1.3 mm",
    properties: ["Mass ≈4.15 million M☉", "EHT image released 2022", "At the Galactic centre"],
    description:
      "The compact gravitational source at the heart of the Milky Way, surrounded by hot orbiting plasma.",
    visualNote: "The EHT ring is false-color radio data; the viewing size is exaggerated.",
    source: "Event Horizon Telescope / ESO GRAVITY",
  }),
  o({
    id: "m87star",
    name: "M87*",
    aliases: ["Virgo A black hole"],
    category: "Black hole",
    subtype: "Supermassive black hole",
    distance: 55e6,
    l: 283.8,
    b: 74.5,
    diameterLy: 0.004,
    visual: "blackhole",
    color: "#ed7435",
    accent: "#ffd06c",
    observed: "Radio interferometry and multiwavelength jet",
    properties: [
      "Mass ≈6.5 billion M☉",
      "First black hole directly imaged",
      "Jet extends thousands of ly",
    ],
    description:
      "The supermassive black hole in Messier 87, source of a prominent relativistic jet and the first EHT black-hole image.",
    visualNote: "The orange EHT ring is false-color radio intensity and is enlarged here.",
    source: "Event Horizon Telescope / NASA",
  }),
  o({
    id: "cygx1",
    name: "Cygnus X-1",
    aliases: ["Cyg X-1"],
    category: "Black hole",
    subtype: "Stellar-mass X-ray binary",
    distance: 7240,
    l: 71.3,
    b: 3.1,
    diameterLy: 4.4e-12,
    visual: "blackhole",
    color: "#ffb65c",
    accent: "#6da9ff",
    observed: "X-ray, optical and radio",
    properties: ["Black hole ≈21 M☉", "Blue-supergiant companion", "Strong X-ray source"],
    description:
      "A stellar black hole feeding from the wind of a massive blue companion, producing a hot accretion flow.",
    visualNote: "The black hole and disk are enlarged; X-rays have no visible-light color.",
    source: "NASA Chandra / peer-reviewed VLBI",
  }),
  o({
    id: "gw150914",
    name: "GW150914",
    aliases: ["First gravitational-wave event"],
    category: "Black hole",
    subtype: "Binary black-hole merger remnant",
    distance: 1.3e9,
    l: 314,
    b: -45,
    diameterLy: 1.3e-11,
    visual: "blackhole",
    color: "#f3a15d",
    accent: "#b87bff",
    observed: "Gravitational waves only",
    properties: [
      "First direct gravitational-wave detection",
      "36 + 29 M☉ progenitors",
      "≈62 M☉ remnant",
    ],
    description:
      "The first directly detected gravitational-wave event, produced by two black holes merging 1.3 billion light-years away.",
    visualNote:
      "No electromagnetic image exists; the visual is a numerical-relativity-inspired interpretation.",
    source: "LIGO / NSF",
  }),
  o({
    id: "siriusb",
    name: "Sirius B",
    aliases: ["WD 0642−166"],
    category: "Stellar remnant",
    subtype: "White dwarf",
    distance: 8.6,
    l: 227.2,
    b: -8.9,
    diameterLy: 1.2e-9,
    visual: "star",
    color: "#e8f5ff",
    accent: "#9fcaff",
    observed: "Visible and ultraviolet",
    properties: ["About one solar mass", "Earth-sized radius", "Temperature ≈25,000 K"],
    description:
      "The nearby dense white-dwarf companion of Sirius A, containing roughly the Sun's mass in an Earth-sized body.",
    visualNote: "Close to true blue-white color, but its rendered radius is enlarged.",
    source: "NASA / ESA Hubble",
  }),
  o({
    id: "sn1987a",
    name: "SN 1987A",
    aliases: ["Supernova 1987A"],
    category: "Stellar remnant",
    subtype: "Young supernova remnant",
    distance: 168000,
    l: 279.7,
    b: -31.9,
    diameterLy: 1.3,
    visual: "remnant",
    color: "#e86065",
    accent: "#89c8ff",
    observed: "Visible, infrared and X-ray",
    properties: [
      "In the Large Magellanic Cloud",
      "Supernova seen in 1987",
      "Bright equatorial ring",
    ],
    description:
      "The nearest supernova observed in the modern era, now revealing expanding debris colliding with a ring of older gas.",
    visualNote: "Composite colors combine Webb, Hubble and Chandra wavelengths.",
    source: "NASA / ESA / CSA Webb",
  }),
  o({
    id: "betelgeuse",
    name: "Betelgeuse",
    aliases: ["Alpha Orionis"],
    category: "Unusual star",
    subtype: "Red supergiant",
    distance: 548,
    l: 199.8,
    b: -9,
    diameterLy: 7.1e-5,
    visual: "star",
    color: "#e75e3c",
    accent: "#ffbd72",
    observed: "Visible, infrared and radio",
    properties: ["Radius ≈764 R☉", "Semiregular variable", "Great Dimming in 2019–2020"],
    description:
      "A nearby red supergiant with a mottled convective surface and heavy mass loss, destined eventually to undergo core collapse.",
    visualNote: "Surface structure is procedural; the reddish color is physically representative.",
    source: "NASA / ESA / ESO",
  }),
  o({
    id: "eta-car",
    name: "Eta Carinae",
    aliases: ["η Carinae"],
    category: "Unusual star",
    subtype: "Luminous blue variable binary",
    distance: 7500,
    l: 287.6,
    b: -0.6,
    diameterLy: 1,
    visual: "bipolar",
    color: "#df7f43",
    accent: "#f8d9a0",
    observed: "Visible, infrared and X-ray",
    properties: ["Massive binary system", "Great Eruption in the 1840s", "Homunculus Nebula ≈1 ly"],
    description:
      "An extremely luminous, unstable massive binary hidden inside bipolar dusty lobes expelled during its nineteenth-century Great Eruption.",
    visualNote: "The lobes use false-color mapping; the central binary remains unresolved here.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "uyscuti",
    name: "UY Scuti",
    aliases: ["BD−12 5055"],
    category: "Unusual star",
    subtype: "Red supergiant",
    distance: 9500,
    l: 14.4,
    b: -0.1,
    diameterLy: 0.00016,
    visual: "star",
    color: "#d94a32",
    accent: "#ff9b54",
    observed: "Visible and infrared",
    properties: ["Very large estimated radius", "Strong stellar mass loss", "Semiregular variable"],
    description:
      "A cool, luminous red supergiant often cited among the largest known stars by estimated radius.",
    visualNote:
      "Its radius and distance carry substantial uncertainty; the surface is illustrative.",
    source: "NASA/IPAC catalogues / astronomical literature",
  }),
  o({
    id: "wr104",
    name: "WR 104",
    aliases: ["Ve 2-45"],
    category: "Unusual star",
    subtype: "Wolf–Rayet binary / pinwheel nebula",
    distance: 8000,
    l: 6.4,
    b: -0.4,
    diameterLy: 0.3,
    visual: "shell",
    color: "#f5d5a3",
    accent: "#e88a45",
    observed: "Infrared interferometry",
    properties: ["Colliding-wind binary", "Rotating dust spiral", "Orbit ≈241.5 days"],
    description:
      "A hot Wolf–Rayet binary whose colliding winds continuously create a rotating spiral plume of warm dust.",
    visualNote: "The infrared pinwheel is rendered in assigned warm colors.",
    source: "NASA/JPL and interferometric observations",
  }),
  o({
    id: "vycma",
    name: "VY Canis Majoris",
    aliases: ["HD 58061"],
    category: "Supergiant",
    subtype: "Red hypergiant",
    distance: 3820,
    l: 239.4,
    b: -5.1,
    diameterLy: 0.0003,
    visual: "star",
    color: "#ff8a52",
    accent: "#ffd7ae",
    observed: "Visible, infrared and submillimeter",
    properties: ["Radius ≈1,400 R☉", "Heavy dust-driven mass loss", "Highly irregular brightness"],
    description:
      "One of the largest known stars, shedding dense clumps and arcs of dust as it approaches the end of its life.",
    visualNote: "The surrounding dust envelope is stylized; its true structure is clumpy and asymmetric.",
    source: "NASA Hubble / SOFIA",
  }),
  o({
    id: "rigel",
    name: "Rigel",
    aliases: ["Beta Orionis"],
    category: "Supergiant",
    subtype: "Blue supergiant",
    distance: 860,
    l: 209.2,
    b: -25.2,
    diameterLy: 0.0000008,
    visual: "star",
    color: "#bcd6ff",
    accent: "#eaf3ff",
    observed: "Visible and ultraviolet",
    properties: ["Spectral type B8 Ia", "≈120,000 L☉", "Multiple-star system"],
    description:
      "A luminous blue supergiant in Orion, hot enough to shine mostly in ultraviolet light.",
    visualNote: "Brightness and glow are compressed so the star stays visible next to fainter objects.",
    source: "ESA Hipparcos / Gaia",
  }),
  o({
    id: "antares",
    name: "Antares",
    aliases: ["Alpha Scorpii"],
    category: "Supergiant",
    subtype: "Red supergiant",
    distance: 550,
    l: 351.9,
    b: 15.1,
    diameterLy: 0.00001,
    visual: "star",
    color: "#ff7f4d",
    accent: "#ffd2a8",
    observed: "Visible, infrared and radio",
    properties: ["Radius ≈680 R☉", "Hot blue companion", "Extended chromosphere"],
    description:
      "The red heart of Scorpius, a cool supergiant whose outer layers are slowly escaping into space.",
    visualNote: "Surface convection cells are illustrative rather than resolved imagery.",
    source: "ESO VLT interferometry",
  }),
  o({
    id: "r136a1",
    name: "R136a1",
    aliases: ["RMC 136a1"],
    category: "Supergiant",
    subtype: "Wolf-Rayet type very massive star",
    distance: 163000,
    l: 279.5,
    b: -31.7,
    diameterLy: 0.0000002,
    visual: "star",
    color: "#cfe0ff",
    accent: "#ffffff",
    observed: "Ultraviolet and visible",
    properties: ["≈200 solar masses", "Millions of times the Sun's output", "In the Tarantula Nebula"],
    description:
      "The most massive star known, part of a dense young cluster in the Large Magellanic Cloud.",
    visualNote: "Its extreme luminosity is scaled down heavily for display.",
    source: "NASA Hubble / ESO",
  }),
  o({
    id: "polaris",
    name: "Polaris",
    aliases: ["North Star", "Alpha Ursae Minoris"],
    category: "Variable star",
    subtype: "Classical Cepheid variable",
    distance: 447,
    l: 123.3,
    b: 26.5,
    diameterLy: 0.0000007,
    visual: "star",
    color: "#ffe7bd",
    accent: "#fff8e8",
    observed: "Visible and ultraviolet",
    properties: ["Pulsation period ≈4 days", "Triple-star system", "Distance standard candle"],
    description:
      "The northern pole star, a pulsating supergiant whose regular rhythm helps calibrate cosmic distances.",
    visualNote: "The pulsation is exaggerated in amplitude so it can be seen.",
    source: "NASA Hubble astrometry",
  }),
  o({
    id: "mira",
    name: "Mira",
    aliases: ["Omicron Ceti"],
    category: "Variable star",
    subtype: "Pulsating red giant with a tail",
    distance: 300,
    l: 167.7,
    b: -57.9,
    diameterLy: 0.0002,
    visual: "star",
    color: "#ff9a63",
    accent: "#ffd9b5",
    observed: "Ultraviolet and visible",
    properties: ["Period ≈332 days", "13 light-year debris tail", "Binary with a white dwarf"],
    description:
      "A dramatically variable red giant racing through space and leaving a long trail of shed material behind it.",
    visualNote: "The tail is shortened relative to its true extent.",
    source: "NASA GALEX",
  }),
  o({
    id: "ttauri",
    name: "T Tauri",
    aliases: ["HD 284419"],
    category: "Variable star",
    subtype: "Young pre-main-sequence star",
    distance: 470,
    l: 176.2,
    b: -20.9,
    diameterLy: 0.00004,
    visual: "star",
    color: "#ffd08a",
    accent: "#9ad4ff",
    observed: "Visible and infrared",
    properties: ["Prototype of T Tauri stars", "Still accreting gas", "Associated reflection nebulosity"],
    description:
      "A newborn star still contracting toward the main sequence, surrounded by leftover material from its birth.",
    visualNote: "The circumstellar dust is a simplified representation.",
    source: "NASA / ESA Hubble",
  }),
  o({
    id: "tabby",
    name: "Tabby's Star",
    aliases: ["KIC 8462852", "Boyajian's Star"],
    category: "Variable star",
    subtype: "Irregularly dimming F-type star",
    distance: 1470,
    l: 73.4,
    b: 3.8,
    diameterLy: 0.0000005,
    visual: "star",
    color: "#f6f2ff",
    accent: "#c4b6ff",
    observed: "Optical photometry and infrared",
    properties: ["Deep irregular dips", "Wavelength-dependent dimming", "Dust is the favored explanation"],
    description:
      "A star famous for sudden, uneven drops in brightness, most likely caused by passing clouds of fine dust.",
    visualNote: "The obscuring dust is illustrative; nothing has been imaged directly.",
    source: "NASA Kepler and follow-up surveys",
  }),
  o({
    id: "algol",
    name: "Algol",
    aliases: ["Beta Persei", "Demon Star"],
    category: "Variable star",
    subtype: "Eclipsing binary",
    distance: 90,
    l: 149,
    b: -14.9,
    diameterLy: 0.0000004,
    visual: "star",
    color: "#dbe8ff",
    accent: "#ffcf9a",
    observed: "Visible photometry and radio",
    properties: ["Eclipse period 2.87 days", "Mass transfer between components", "Triple system"],
    description:
      "A close pair of stars that regularly eclipse each other, dimming noticeably every few days.",
    visualNote: "The pair is shown widely separated for clarity.",
    source: "NASA / ESA archival photometry",
  }),
  o({
    id: "proxima",
    name: "Proxima Centauri",
    aliases: ["Alpha Centauri C", "V645 Cen"],
    category: "Dwarf star",
    subtype: "Red dwarf flare star",
    distance: 4.24,
    l: 313.9,
    b: -1.9,
    diameterLy: 0.0000002,
    visual: "star",
    color: "#ff7a55",
    accent: "#ffc9a3",
    observed: "Visible, X-ray and radio",
    properties: ["Nearest star to the Sun", "Powerful flares", "Hosts Proxima b"],
    description:
      "The closest star to the Sun: a small, cool red dwarf that erupts in bright flares and hosts at least one planet.",
    visualNote: "Flare brightness is compressed to remain viewable.",
    source: "NASA Hubble / ESO",
  }),
  o({
    id: "luhman16",
    name: "Luhman 16",
    aliases: ["WISE 1049-5319"],
    category: "Dwarf star",
    subtype: "Brown dwarf binary",
    distance: 6.5,
    l: 279,
    b: 9.6,
    diameterLy: 0.0000002,
    visual: "star",
    color: "#a2624a",
    accent: "#e2a37d",
    observed: "Infrared imaging and spectroscopy",
    properties: ["Nearest brown dwarf pair", "Cloudy, banded atmospheres", "Too small to fuse hydrogen"],
    description:
      "A pair of failed stars just a few light-years away, glowing faintly in infrared with weather-like cloud bands.",
    visualNote: "Colors approximate infrared brightness, not visible light.",
    source: "NASA Spitzer / ESO",
  }),
  o({
    id: "vanmaanen",
    name: "Van Maanen's Star",
    aliases: ["Van Maanen 2", "WD 0046+051"],
    category: "Dwarf star",
    subtype: "Solitary white dwarf",
    distance: 14.1,
    l: 121.9,
    b: -57.5,
    diameterLy: 0.0000000015,
    visual: "star",
    color: "#eaf1ff",
    accent: "#a9c6ff",
    observed: "Visible and ultraviolet spectroscopy",
    properties: ["Nearest single white dwarf", "Earth-sized", "Polluted by accreted debris"],
    description:
      "A dense, cooling stellar core the size of Earth, its atmosphere contaminated by shredded leftover planetary material.",
    visualNote: "Its physical size is far below the display minimum and is enlarged.",
    source: "NASA / ESA archival spectroscopy",
  }),
  o({
    id: "methuselah",
    name: "Methuselah Star",
    aliases: ["HD 140283"],
    category: "Dwarf star",
    subtype: "Ancient metal-poor subgiant",
    distance: 200,
    l: 356.4,
    b: 39.6,
    diameterLy: 0.0000001,
    visual: "star",
    color: "#fff2d0",
    accent: "#ffdca0",
    observed: "Visible spectroscopy and parallax",
    properties: ["One of the oldest known stars", "Extremely low metal content", "High-velocity halo orbit"],
    description:
      "A survivor from the early universe, nearly devoid of heavy elements and racing through the galactic halo.",
    visualNote: "Appearance is a plain stellar rendering; no imagery resolves its surface.",
    source: "NASA Hubble astrometry",
  }),
  o({
    id: "regulus",
    name: "Regulus",
    aliases: ["Alpha Leonis"],
    category: "Dwarf star",
    subtype: "Rapidly rotating main-sequence star",
    distance: 79,
    l: 226.4,
    b: 48.9,
    diameterLy: 0.0000002,
    visual: "star",
    color: "#cfe2ff",
    accent: "#ffffff",
    observed: "Visible and interferometric",
    properties: ["Spins near break-up speed", "Strongly flattened shape", "White-dwarf companion"],
    description:
      "A hot blue-white star spinning so fast it bulges at its equator and shines unevenly across its surface.",
    visualNote: "The oblate shape is emphasized for visibility.",
    source: "CHARA interferometry / NASA archives",
  }),
];

export const OBJECT_BY_ID = new Map(OBSERVED_OBJECTS.map((item) => [item.id, item]));
export const OBJECT_CATEGORIES: ObjectCategory[] = [
  "Quasar",
  "Neutron star",
  "Black hole",
  "Stellar remnant",
  "Unusual star",
  "Supergiant",
  "Variable star",
  "Dwarf star",
];

export function objectPosition(
  item: Pick<ObservedObject, "l" | "b" | "distance">,
): [number, number, number] {
  const lr = (item.l * Math.PI) / 180,
    br = (item.b * Math.PI) / 180,
    c = Math.cos(br);
  return [
    -item.distance * c * Math.cos(lr),
    item.distance * Math.sin(br),
    item.distance * c * Math.sin(lr),
  ];
}

export function objectVisitDistance(item: ObservedObject): number {
  if (item.diameterLy >= 0.05) return Math.max(item.diameterLy * 1.8, 0.2);
  // Compact remnants use a minimum presentation scale of 2e-7 ly in the
  // renderer. Keep the camera outside that model instead of inside its beams.
  return Math.max(item.diameterLy * 24, 8e-7);
}
