export type ObjectCategory =
  | "Nebula"
  | "Quasar"
  | "Neutron star"
  | "Black hole"
  | "Stellar remnant"
  | "Unusual star";
export type ObjectVisual =
  | "cloud"
  | "shell"
  | "bipolar"
  | "jet"
  | "pulsar"
  | "blackhole"
  | "star"
  | "remnant";

export type ObservedObject = {
  id: string;
  name: string;
  aliases: string[];
  category: ObjectCategory;
  subtype: string;
  distance: number;
  l: number;
  b: number;
  diameterLy: number;
  visual: ObjectVisual;
  color: string;
  accent: string;
  observed: string;
  properties: string[];
  description: string;
  visualNote: string;
  source: string;
};

const o = (x: ObservedObject) => x;
export const OBSERVED_OBJECTS: ObservedObject[] = [
  o({
    id: "m1",
    name: "Crab Nebula",
    aliases: ["M1", "NGC 1952"],
    category: "Nebula",
    subtype: "Supernova remnant / pulsar-wind nebula",
    distance: 6500,
    l: 184.6,
    b: -5.8,
    diameterLy: 11,
    visual: "remnant",
    color: "#ef744d",
    accent: "#65cfff",
    observed: "Optical, infrared, X-ray and radio composite",
    properties: ["Remnant of SN 1054", "Expansion ≈1,500 km/s", "Contains the 33 ms Crab Pulsar"],
    description:
      "Expanding debris from the supernova recorded in 1054. Dense ionized filaments surround a blue synchrotron nebula powered by its central pulsar.",
    visualNote: "Colors map several wavelengths and emission lines; they are not a naked-eye view.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "m42",
    name: "Orion Nebula",
    aliases: ["M42", "NGC 1976"],
    category: "Nebula",
    subtype: "Emission and reflection nebula",
    distance: 1344,
    l: 209,
    b: -19.4,
    diameterLy: 24,
    visual: "cloud",
    color: "#e98983",
    accent: "#71d7c8",
    observed: "Visible and narrowband optical",
    properties: [
      "Nearest large star-forming region",
      "Hosts the Trapezium cluster",
      "About 24 ly across",
    ],
    description:
      "A nearby stellar nursery where ultraviolet radiation from young stars illuminates and sculpts gas and dust.",
    visualNote: "The pink, teal and green mapping emphasizes hydrogen and oxygen emission.",
    source: "NASA / ESA Hubble",
  }),
  o({
    id: "m16",
    name: "Eagle Nebula",
    aliases: ["M16", "Pillars of Creation"],
    category: "Nebula",
    subtype: "Star-forming emission nebula",
    distance: 6500,
    l: 17,
    b: 0.8,
    diameterLy: 70,
    visual: "cloud",
    color: "#c98a54",
    accent: "#77a9d8",
    observed: "Visible and infrared",
    properties: [
      "Pillars are 4–5 ly tall",
      "Active star formation",
      "Ionized by young massive stars",
    ],
    description:
      "A vast star-forming cloud containing the Pillars of Creation, columns of gas and dust eroded by nearby hot stars.",
    visualNote: "Rendered in the familiar Hubble/JWST-inspired wavelength mapping.",
    source: "NASA / ESA Hubble and Webb",
  }),
  o({
    id: "helix",
    name: "Helix Nebula",
    aliases: ["NGC 7293", "Eye of God"],
    category: "Nebula",
    subtype: "Planetary nebula",
    distance: 655,
    l: 36.1,
    b: -57.1,
    diameterLy: 2.5,
    visual: "shell",
    color: "#df5b4f",
    accent: "#4fd4cb",
    observed: "Optical and infrared composite",
    properties: [
      "One of the nearest planetary nebulae",
      "White-dwarf central star",
      "Disk-like shell geometry",
    ],
    description:
      "Outer layers shed by a dying Sun-like star form a tilted, expanding ring with cometary knots.",
    visualNote:
      "Blue-green and red identify different ionized gases rather than literal eye color.",
    source: "NASA Hubble / Spitzer",
  }),
  o({
    id: "m57",
    name: "Ring Nebula",
    aliases: ["M57", "NGC 6720"],
    category: "Nebula",
    subtype: "Planetary nebula",
    distance: 2283,
    l: 63.2,
    b: 13.9,
    diameterLy: 1.3,
    visual: "shell",
    color: "#e46051",
    accent: "#55d8c4",
    observed: "Visible and infrared composite",
    properties: ["Barrel-like shell", "Hot white-dwarf core", "About 1.3 ly wide"],
    description:
      "A dying star's ionized envelope viewed nearly down its axis, producing its familiar luminous ring.",
    visualNote: "Its multi-color appearance is wavelength mapped.",
    source: "NASA / ESA / CSA Webb and Hubble",
  }),
  o({
    id: "veil",
    name: "Veil Nebula",
    aliases: ["Cygnus Loop"],
    category: "Nebula",
    subtype: "Supernova remnant",
    distance: 2400,
    l: 74,
    b: -8.5,
    diameterLy: 110,
    visual: "remnant",
    color: "#ed604d",
    accent: "#5ad0dd",
    observed: "Narrowband optical",
    properties: ["≈110 ly across", "10,000–20,000 years old", "Thin shock filaments"],
    description:
      "A huge expanding supernova blast wave whose shock fronts form delicate, intertwined filaments.",
    visualNote: "Filament colors map sulfur, hydrogen and oxygen emission.",
    source: "NASA / ESA Hubble",
  }),
  o({
    id: "carina",
    name: "Carina Nebula",
    aliases: ["NGC 3372"],
    category: "Nebula",
    subtype: "Massive star-forming region",
    distance: 7500,
    l: 287.4,
    b: -0.6,
    diameterLy: 300,
    visual: "cloud",
    color: "#d99659",
    accent: "#559dd2",
    observed: "Infrared and visible composite",
    properties: ["≈300 ly across", "Contains Eta Carinae", "Many massive young stars"],
    description:
      "One of the Milky Way's largest stellar nurseries, filled with dust pillars, cavities and massive stars.",
    visualNote: "Infrared false color reveals structures hidden by dust.",
    source: "NASA / ESA / CSA Webb",
  }),
  o({
    id: "boomerang",
    name: "Boomerang Nebula",
    aliases: ["Centaurus Bipolar Nebula"],
    category: "Nebula",
    subtype: "Protoplanetary nebula",
    distance: 5000,
    l: 303.4,
    b: 7.1,
    diameterLy: 2,
    visual: "bipolar",
    color: "#78bff0",
    accent: "#d8efff",
    observed: "Visible and millimeter wavelengths",
    properties: ["Bipolar outflow", "Gas temperature ≈1 K", "Coldest known natural environment"],
    description:
      "Rapidly expanding gas from a dying star forms two lobes and cools below the cosmic microwave background.",
    visualNote: "The blue appearance is an assigned visualization color.",
    source: "NASA / ESA Hubble / ALMA",
  }),
  o({
    id: "cats-eye",
    name: "Cat's Eye Nebula",
    aliases: ["NGC 6543"],
    category: "Nebula",
    subtype: "Planetary nebula",
    distance: 3300,
    l: 96.4,
    b: 29.9,
    diameterLy: 0.2,
    visual: "shell",
    color: "#5ad6bb",
    accent: "#e1a05d",
    observed: "Narrowband visible and X-ray",
    properties: ["Nested gas shells", "Fast stellar wind", "Extended halo ≈5 ly"],
    description:
      "Multiple mass-loss episodes created nested shells, knots and jets around a hot dying star.",
    visualNote: "Contrasting colors separate ionized gases and X-ray emission.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "butterfly",
    name: "Butterfly Nebula",
    aliases: ["NGC 6302", "Bug Nebula"],
    category: "Nebula",
    subtype: "Bipolar planetary nebula",
    distance: 3800,
    l: 349.5,
    b: 1.1,
    diameterLy: 3.4,
    visual: "bipolar",
    color: "#e77849",
    accent: "#6fc9ec",
    observed: "Visible and infrared",
    properties: ["Dusty equatorial torus", "Central star ≈250,000 K", "High-speed bipolar lobes"],
    description:
      "A dense dust belt funnels gas from an extremely hot central star into opposing wing-like lobes.",
    visualNote: "The dramatic colors combine emission lines and infrared observations.",
    source: "NASA / ESA Hubble / Webb",
  }),
  o({
    id: "3c273",
    name: "3C 273",
    aliases: ["PGC 41121"],
    category: "Quasar",
    subtype: "Optically bright quasar",
    distance: 2.4e9,
    l: 290,
    b: 64.4,
    diameterLy: 200000,
    visual: "jet",
    color: "#dff2ff",
    accent: "#78a9ff",
    observed: "Unresolved nucleus; optical/X-ray jet",
    properties: ["Redshift z=0.158", "First identified quasar", "Jet ≈200,000 ly"],
    description:
      "A brilliant active galactic nucleus powered by matter falling toward a supermassive black hole, with a large relativistic jet.",
    visualNote: "The central engine is unresolved; its disk and jet are enhanced for inspection.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "3c279",
    name: "3C 279",
    aliases: ["4C -05.55"],
    category: "Quasar",
    subtype: "Blazar / flat-spectrum quasar",
    distance: 5.4e9,
    l: 305.1,
    b: 57.1,
    diameterLy: 100000,
    visual: "jet",
    color: "#fff2d8",
    accent: "#759cff",
    observed: "Gamma-ray, radio and optical",
    properties: ["Redshift z=0.536", "Jet points near Earth", "Apparent superluminal motion"],
    description:
      "A rapidly variable blazar whose relativistic jet is aimed close to our line of sight.",
    visualNote: "Jet motion is relativistic projection; the model is illustrative.",
    source: "NASA Fermi / VLBI observations",
  }),
  o({
    id: "mrk231",
    name: "Markarian 231",
    aliases: ["Mrk 231", "UGC 8058"],
    category: "Quasar",
    subtype: "Nearest known quasar / ULIRG",
    distance: 581e6,
    l: 196.5,
    b: 72.9,
    diameterLy: 100000,
    visual: "jet",
    color: "#ffe0bb",
    accent: "#78a9e8",
    observed: "Ultraviolet, visible and infrared",
    properties: ["Distance ≈581 Mly", "Powerful molecular outflow", "Disturbed host galaxy"],
    description:
      "The nearest quasar, embedded in a luminous merging galaxy and driving a powerful outflow.",
    visualNote:
      "The luminous nucleus is exaggerated; a proposed binary black hole remains uncertain.",
    source: "NASA Hubble",
  }),
  o({
    id: "ton618",
    name: "TON 618",
    aliases: ["FBQS J122824.9+312837"],
    category: "Quasar",
    subtype: "Hyperluminous quasar",
    distance: 10.4e9,
    l: 187.4,
    b: 83,
    diameterLy: 150000,
    visual: "jet",
    color: "#ffd9bd",
    accent: "#8da5ff",
    observed: "Unresolved optical point and spectrum",
    properties: [
      "Redshift z≈2.219",
      "Ultramassive black-hole estimate",
      "Seen billions of years in the past",
    ],
    description:
      "An exceptionally luminous distant quasar associated with one of the largest published black-hole mass estimates.",
    visualNote: "Its exact black-hole mass is model-dependent; the source is unresolved.",
    source: "NASA/IPAC catalogues and peer-reviewed spectroscopy",
  }),
  o({
    id: "crab-pulsar",
    name: "Crab Pulsar",
    aliases: ["PSR B0531+21"],
    category: "Neutron star",
    subtype: "Young rotation-powered pulsar",
    distance: 6500,
    l: 184.6,
    b: -5.8,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#dff7ff",
    accent: "#4bbfff",
    observed: "Radio through gamma ray",
    properties: ["Spin period 33 ms", "Diameter ≈20 km", "Powers the Crab Nebula"],
    description:
      "The collapsed stellar core left by SN 1054, sweeping radiation beams across Earth about 30 times each second.",
    visualNote: "The star and beams are enormously enlarged for visibility.",
    source: "NASA Chandra",
  }),
  o({
    id: "vela",
    name: "Vela Pulsar",
    aliases: ["PSR B0833−45"],
    category: "Neutron star",
    subtype: "Young pulsar",
    distance: 960,
    l: 263.6,
    b: -2.8,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#e6fbff",
    accent: "#4b9fff",
    observed: "Radio, optical, X-ray and gamma ray",
    properties: ["Spin period 89 ms", "Inside the Vela remnant", "X-ray torus and jets"],
    description:
      "A nearby young neutron star whose wind creates moving arcs and jet-like X-ray structures.",
    visualNote: "The compact star and magnetic beams are not rendered to scale.",
    source: "NASA Chandra / Fermi",
  }),
  o({
    id: "b1919",
    name: "First Pulsar",
    aliases: ["PSR B1919+21", "CP 1919", "LGM-1"],
    category: "Neutron star",
    subtype: "Radio pulsar",
    distance: 2283,
    l: 55.8,
    b: 3.5,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#f2fbff",
    accent: "#8fc7ff",
    observed: "Radio pulses",
    properties: ["Spin period 1.337 s", "Discovered in 1967", "First recognized pulsar"],
    description:
      "The first pulsar ever identified, discovered by Jocelyn Bell Burnell through its exceptionally regular radio pulses.",
    visualNote: "Radio beams are an explanatory visualization, not visible light.",
    source: "NRAO / peer-reviewed discovery record",
  }),
  o({
    id: "sgr1806",
    name: "SGR 1806−20",
    aliases: ["SGR 1806-20"],
    category: "Neutron star",
    subtype: "Magnetar",
    distance: 50000,
    l: 9.9,
    b: -0.2,
    diameterLy: 2.1e-12,
    visual: "pulsar",
    color: "#f7eeff",
    accent: "#d267ff",
    observed: "X-ray and gamma ray",
    properties: ["Magnetic field ≈10¹⁵ G", "Giant flare in 2004", "Distance is highly uncertain"],
    description:
      "An intensely magnetized neutron star that produced the brightest extrasolar gamma-ray flare yet recorded.",
    visualNote:
      "Magnetic loops and scale are illustrative; distance estimates span roughly 28–50 kly.",
    source: "NASA Goddard / Chandra",
  }),
  o({
    id: "j0348",
    name: "PSR J0348+0432",
    aliases: ["J0348+0432"],
    category: "Neutron star",
    subtype: "Massive neutron-star binary",
    distance: 6500,
    l: 183.3,
    b: -36.8,
    diameterLy: 2.7e-12,
    visual: "pulsar",
    color: "#e8f4ff",
    accent: "#77a8ff",
    observed: "Radio timing and optical companion",
    properties: ["Mass 2.01 ± 0.04 M☉", "White-dwarf companion", "Tests strong-field gravity"],
    description:
      "A precisely weighed, unusually massive neutron star in a compact binary used to test general relativity.",
    visualNote: "Both bodies and their separation are enhanced for close viewing.",
    source: "Peer-reviewed radio timing / ESO",
  }),
  o({
    id: "sgr-a",
    name: "Sagittarius A*",
    aliases: ["Sgr A*"],
    category: "Black hole",
    subtype: "Milky Way central supermassive black hole",
    distance: 26673,
    l: 0,
    b: 0,
    diameterLy: 1.3e-5,
    visual: "blackhole",
    color: "#f59a48",
    accent: "#fff0be",
    observed: "Radio interferometry at 1.3 mm",
    properties: ["Mass ≈4.15 million M☉", "EHT image released 2022", "At the Galactic centre"],
    description:
      "The compact gravitational source at the heart of the Milky Way, surrounded by hot orbiting plasma.",
    visualNote: "The EHT ring is false-color radio data; the viewing size is exaggerated.",
    source: "Event Horizon Telescope / ESO GRAVITY",
  }),
  o({
    id: "m87star",
    name: "M87*",
    aliases: ["Virgo A black hole"],
    category: "Black hole",
    subtype: "Supermassive black hole",
    distance: 55e6,
    l: 283.8,
    b: 74.5,
    diameterLy: 0.004,
    visual: "blackhole",
    color: "#ed7435",
    accent: "#ffd06c",
    observed: "Radio interferometry and multiwavelength jet",
    properties: [
      "Mass ≈6.5 billion M☉",
      "First black hole directly imaged",
      "Jet extends thousands of ly",
    ],
    description:
      "The supermassive black hole in Messier 87, source of a prominent relativistic jet and the first EHT black-hole image.",
    visualNote: "The orange EHT ring is false-color radio intensity and is enlarged here.",
    source: "Event Horizon Telescope / NASA",
  }),
  o({
    id: "cygx1",
    name: "Cygnus X-1",
    aliases: ["Cyg X-1"],
    category: "Black hole",
    subtype: "Stellar-mass X-ray binary",
    distance: 7240,
    l: 71.3,
    b: 3.1,
    diameterLy: 4.4e-12,
    visual: "blackhole",
    color: "#ffb65c",
    accent: "#6da9ff",
    observed: "X-ray, optical and radio",
    properties: ["Black hole ≈21 M☉", "Blue-supergiant companion", "Strong X-ray source"],
    description:
      "A stellar black hole feeding from the wind of a massive blue companion, producing a hot accretion flow.",
    visualNote: "The black hole and disk are enlarged; X-rays have no visible-light color.",
    source: "NASA Chandra / peer-reviewed VLBI",
  }),
  o({
    id: "gw150914",
    name: "GW150914",
    aliases: ["First gravitational-wave event"],
    category: "Black hole",
    subtype: "Binary black-hole merger remnant",
    distance: 1.3e9,
    l: 314,
    b: -45,
    diameterLy: 1.3e-11,
    visual: "blackhole",
    color: "#f3a15d",
    accent: "#b87bff",
    observed: "Gravitational waves only",
    properties: [
      "First direct gravitational-wave detection",
      "36 + 29 M☉ progenitors",
      "≈62 M☉ remnant",
    ],
    description:
      "The first directly detected gravitational-wave event, produced by two black holes merging 1.3 billion light-years away.",
    visualNote:
      "No electromagnetic image exists; the visual is a numerical-relativity-inspired interpretation.",
    source: "LIGO / NSF",
  }),
  o({
    id: "siriusb",
    name: "Sirius B",
    aliases: ["WD 0642−166"],
    category: "Stellar remnant",
    subtype: "White dwarf",
    distance: 8.6,
    l: 227.2,
    b: -8.9,
    diameterLy: 1.2e-9,
    visual: "star",
    color: "#e8f5ff",
    accent: "#9fcaff",
    observed: "Visible and ultraviolet",
    properties: ["About one solar mass", "Earth-sized radius", "Temperature ≈25,000 K"],
    description:
      "The nearby dense white-dwarf companion of Sirius A, containing roughly the Sun's mass in an Earth-sized body.",
    visualNote: "Close to true blue-white color, but its rendered radius is enlarged.",
    source: "NASA / ESA Hubble",
  }),
  o({
    id: "sn1987a",
    name: "SN 1987A",
    aliases: ["Supernova 1987A"],
    category: "Stellar remnant",
    subtype: "Young supernova remnant",
    distance: 168000,
    l: 279.7,
    b: -31.9,
    diameterLy: 1.3,
    visual: "remnant",
    color: "#e86065",
    accent: "#89c8ff",
    observed: "Visible, infrared and X-ray",
    properties: [
      "In the Large Magellanic Cloud",
      "Supernova seen in 1987",
      "Bright equatorial ring",
    ],
    description:
      "The nearest supernova observed in the modern era, now revealing expanding debris colliding with a ring of older gas.",
    visualNote: "Composite colors combine Webb, Hubble and Chandra wavelengths.",
    source: "NASA / ESA / CSA Webb",
  }),
  o({
    id: "betelgeuse",
    name: "Betelgeuse",
    aliases: ["Alpha Orionis"],
    category: "Unusual star",
    subtype: "Red supergiant",
    distance: 548,
    l: 199.8,
    b: -9,
    diameterLy: 7.1e-5,
    visual: "star",
    color: "#e75e3c",
    accent: "#ffbd72",
    observed: "Visible, infrared and radio",
    properties: ["Radius ≈764 R☉", "Semiregular variable", "Great Dimming in 2019–2020"],
    description:
      "A nearby red supergiant with a mottled convective surface and heavy mass loss, destined eventually to undergo core collapse.",
    visualNote: "Surface structure is procedural; the reddish color is physically representative.",
    source: "NASA / ESA / ESO",
  }),
  o({
    id: "eta-car",
    name: "Eta Carinae",
    aliases: ["η Carinae"],
    category: "Unusual star",
    subtype: "Luminous blue variable binary",
    distance: 7500,
    l: 287.6,
    b: -0.6,
    diameterLy: 1,
    visual: "bipolar",
    color: "#df7f43",
    accent: "#f8d9a0",
    observed: "Visible, infrared and X-ray",
    properties: ["Massive binary system", "Great Eruption in the 1840s", "Homunculus Nebula ≈1 ly"],
    description:
      "An extremely luminous, unstable massive binary hidden inside bipolar dusty lobes expelled during its nineteenth-century Great Eruption.",
    visualNote: "The lobes use false-color mapping; the central binary remains unresolved here.",
    source: "NASA Hubble / Chandra",
  }),
  o({
    id: "uyscuti",
    name: "UY Scuti",
    aliases: ["BD−12 5055"],
    category: "Unusual star",
    subtype: "Red supergiant",
    distance: 9500,
    l: 14.4,
    b: -0.1,
    diameterLy: 0.00016,
    visual: "star",
    color: "#d94a32",
    accent: "#ff9b54",
    observed: "Visible and infrared",
    properties: ["Very large estimated radius", "Strong stellar mass loss", "Semiregular variable"],
    description:
      "A cool, luminous red supergiant often cited among the largest known stars by estimated radius.",
    visualNote:
      "Its radius and distance carry substantial uncertainty; the surface is illustrative.",
    source: "NASA/IPAC catalogues / astronomical literature",
  }),
  o({
    id: "wr104",
    name: "WR 104",
    aliases: ["Ve 2-45"],
    category: "Unusual star",
    subtype: "Wolf–Rayet binary / pinwheel nebula",
    distance: 8000,
    l: 6.4,
    b: -0.4,
    diameterLy: 0.3,
    visual: "shell",
    color: "#f5d5a3",
    accent: "#e88a45",
    observed: "Infrared interferometry",
    properties: ["Colliding-wind binary", "Rotating dust spiral", "Orbit ≈241.5 days"],
    description:
      "A hot Wolf–Rayet binary whose colliding winds continuously create a rotating spiral plume of warm dust.",
    visualNote: "The infrared pinwheel is rendered in assigned warm colors.",
    source: "NASA/JPL and interferometric observations",
  }),
];

export const OBJECT_BY_ID = new Map(OBSERVED_OBJECTS.map((item) => [item.id, item]));
export const OBJECT_CATEGORIES: ObjectCategory[] = [
  "Nebula",
  "Quasar",
  "Neutron star",
  "Black hole",
  "Stellar remnant",
  "Unusual star",
];

export function objectPosition(
  item: Pick<ObservedObject, "l" | "b" | "distance">,
): [number, number, number] {
  const lr = (item.l * Math.PI) / 180,
    br = (item.b * Math.PI) / 180,
    c = Math.cos(br);
  return [
    -item.distance * c * Math.cos(lr),
    item.distance * Math.sin(br),
    item.distance * c * Math.sin(lr),
  ];
}

export function objectVisitDistance(item: ObservedObject): number {
  if (item.diameterLy >= 0.05) return Math.max(item.diameterLy * 1.8, 0.2);
  return Math.max(item.diameterLy * 24, 2e-7);
}
